naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  MaxLineLength:
    maxLineLength: 140
  ReturnCount:
    max: 6

complexity:
  LongParameterList:
    constructorThreshold: 8
    ignoreAnnotated: ['Composable']
  LongMethod:
    ignoreAnnotated: ['Composable']

exceptions:
  TooGenericExceptionCaught:
    active: false
